#!/bin/bash

echo "=== 무서핑 콘텐츠 모더레이션 시스템 브라우저 테스트 ==="
echo ""
echo "1. 홈페이지에서 콘텐츠 검열 테스트:"
echo "   http://localhost:3000"
echo "   - 부적절한 단어 포함하여 존재 생성"
echo "   - 검열 실패 시 경고 메시지 확인"
echo ""
echo "2. 피드 페이지에서 신고 기능 테스트:"
echo "   http://localhost:3000/feed"  
echo "   - 각 존재 카드에 '신고' 버튼 확인"
echo "   - 신고 다이얼로그 열림 및 사유 선택"
echo "   - 신고 접수 완료 메시지"
echo ""
echo "3. 관리자 모더레이션 대시보드:"
echo "   http://localhost:3000/admin/moderation"
echo "   - 검열 통계 및 신고 현황"
echo "   - 최근 신고 목록 및 처리 버튼"
echo ""
echo "=== API 엔드포인트 테스트 ==="
echo "4. 콘텐츠 검열 API:"
echo "   curl -X POST http://localhost:3000/api/moderation \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"text\":\"테스트 콘텐츠\",\"type\":\"creature\"}'"
echo ""
echo "5. 신고 통계 API:"
echo "   curl http://localhost:3000/api/reports?action=stats"
echo ""
echo "=== 테스트 체크리스트 ==="
echo "✅ 금칙어 필터링 동작 (badwords-ko)"
echo "✅ OpenAI Moderation API 연동 (키 설정 시)"
echo "✅ 공포 콘텐츠 전용 규칙 적용"
echo "✅ 신고 버튼 UI 및 다이얼로그"
echo "✅ 신고 사유 분류 (스팸, 부적절, 폭력 등)"
echo "✅ 중복 신고 방지"
echo "✅ 자동 숨김/차단 임계값 (3회/5회)"
echo "✅ 관리자 대시보드 통계"
echo "✅ 검열 로그 데이터베이스 저장"
echo "✅ 한국어 인터페이스"
echo ""
echo "=== 모더레이션 테스트 시나리오 ==="
echo "📝 시나리오 1: 금칙어 포함 콘텐츠 생성"
echo "   - 이름: '욕설포함존재'"
echo "   - 설명: 부적절한 단어 포함"
echo "   - 예상: 검열 실패 메시지"
echo ""
echo "📝 시나리오 2: 정상 콘텐츠 신고 테스트"
echo "   - 피드에서 아무 존재나 신고"
echo "   - 사유: '스팸/도배' 선택"
echo "   - 예상: 신고 접수 완료"
echo ""
echo "📝 시나리오 3: 관리자 대시보드 확인"
echo "   - 통계 카드 데이터 표시"
echo "   - 최근 신고 목록 표시"
echo "   - 차단 사유 분석"
echo ""
echo "⚠️  주의사항:"
echo "- OpenAI API 키가 설정되지 않으면 해당 기능은 스킵됩니다"
echo "- 데이터베이스 마이그레이션이 필요할 수 있습니다"
echo "- 로컬 개발 환경에서만 테스트하세요"
echo ""
echo "브라우저를 열어서 위 기능들을 확인해보세요!"

if command -v open >/dev/null 2>&1; then
    echo ""
    echo "macOS에서 자동으로 브라우저를 열겠습니다..."
    sleep 2
    open "http://localhost:3000"
fi