#!/bin/bash

echo "=== 무서핑 게이미피케이션 시스템 브라우저 테스트 ==="
echo ""
echo "1. 홈페이지 헤더의 배지 시스템 확인:"
echo "   http://localhost:3000"
echo "   - 헤더 우측에 'Lv.1' 레벨 표시"
echo "   - 배지 개수 표시"
echo "   - 클릭 시 배지/업적 다이얼로그 열림"
echo ""
echo "2. 게임 페이지의 배지 시스템:"
echo "   http://localhost:3000/game"
echo "   - 좌측 사이드바에 배지 시스템 표시"
echo "   - 게임 점수에 따른 배지 획득"
echo "   - 실시간 경험치 업데이트"
echo ""
echo "3. 프로필 페이지 (배지 다이얼로그):"
echo "   - 프로필, 업적, 통계 탭"
echo "   - 레벨 진행도 바"
echo "   - 획득/미획득 배지 분류"
echo "   - 배지 레어도별 색상 구분"
echo ""
echo "=== 테스트 체크리스트 ==="
echo "✅ 헤더에 레벨 및 배지 수 표시"
echo "✅ 배지 다이얼로그 정상 열림"
echo "✅ 프로필 탭: 레벨, 경험치, 진행도 표시"
echo "✅ 업적 탭: 획득/미획득 배지 목록"
echo "✅ 통계 탭: 사용자 활동 통계"
echo "✅ 게임 점수 연동 (gameScore prop)"
echo "✅ 배지 레어도별 스타일링"
echo "✅ 한국어 텍스트 정상 표시"
echo "✅ API 응답 정상 (/api/achievements)"
echo ""
echo "=== 배지 시스템 테스트 ==="
echo "📍 현재 기본 상태: 익명 사용자, Lv.1, 0 EXP"
echo "🎮 게임에서 점수를 획득하여 '게임 입문자' 배지 테스트"
echo "📝 존재를 생성하여 '첫 번째 존재' 배지 테스트"
echo "❤️  좋아요를 받아 '첫 번째 공감' 배지 테스트"
echo ""
echo "브라우저를 열어서 위 기능들을 확인해보세요!"

if command -v open >/dev/null 2>&1; then
    echo ""
    echo "macOS에서 자동으로 브라우저를 열겠습니다..."
    sleep 2
    open "http://localhost:3000"
fi