#!/bin/bash

echo "=== 무서핑 Google AdSense 연동 브라우저 테스트 ==="
echo ""
echo "1. 홈페이지 광고 배치 확인:"
echo "   http://localhost:3000"
echo "   - 헤더 배너 광고 (상단)"
echo "   - 사이드바 광고 (우측, 데스크탑만)"
echo "   - 모바일 앵커 광고 (하단 고정, 모바일만)"
echo ""
echo "2. 피드 페이지 광고 확인:"
echo "   http://localhost:3000/feed"
echo "   - 헤더 배너 광고"
echo "   - 피드 인라인 광고 (3번째 게시물 뒤)"
echo "   - 콘텐츠 하단 광고"
echo "   - 모바일 앵커 광고"
echo ""
echo "3. 게임 페이지 광고 확인:"
echo "   http://localhost:3000/game"
echo "   - 게임 전용 광고 (좌측 사이드바)"
echo "   - 모바일 앵커 광고"
echo ""
echo "4. 랭킹 페이지 확인:"
echo "   http://localhost:3000/rankings"
echo ""
echo "=== 광고 시스템 테스트 항목 ==="
echo "✅ 테스트 모드 광고 플레이스홀더 표시"
echo "✅ 반응형 광고 단위 (데스크탑/모바일)"
echo "✅ 광고 슬롯 ID 설정"
echo "✅ AdSense 스크립트 로드"
echo "✅ 광고 배치 전략 (헤더, 사이드바, 인라인, 하단)"
echo "✅ 모바일 앵커 광고 (하단 고정)"
echo "✅ 콘텐츠 정책 준수 유틸리티"
echo "✅ 광고 차단 감지 (선택적)"
echo "✅ 무효 클릭 방지 시스템"
echo ""
echo "=== AdSense 정책 준수 체크 ==="
echo "📋 콘텐츠 분석 및 광고 게재 가능성 판단"
echo "📋 공포 콘텐츠 등급 분류 (general/teen/mature)"
echo "📋 과도한 폭력성 콘텐츠 필터링"
echo "📋 성인/음란 콘텐츠 차단"
echo "📋 도박/약물/혐오 표현 제한"
echo "📋 청소년 유해 콘텐츠 경고"
echo ""
echo "=== 현재 상태 ==="
echo "🔧 테스트 모드: 실제 AdSense 대신 플레이스홀더 표시"
echo "🔧 Publisher ID: 환경변수 설정 필요 (NEXT_PUBLIC_ADSENSE_PUBLISHER_ID)"
echo "🔧 광고 슬롯 ID: 실제 승인 후 교체 필요"
echo ""
echo "=== 실제 운영 시 필요한 작업 ==="
echo "1. Google AdSense 계정 생성 및 사이트 등록"
echo "2. 콘텐츠 정책 검토 및 승인 대기"
echo "3. Publisher ID 및 광고 슬롯 ID 설정"
echo "4. 환경변수 NEXT_PUBLIC_ADSENSE_PUBLISHER_ID 설정"
echo "5. 광고 성과 모니터링 및 최적화"
echo ""
echo "⚠️  주의사항:"
echo "- 공포 콘텐츠 특성상 AdSense 승인에 어려움이 있을 수 있음"
echo "- 콘텐츠 품질 관리 및 정책 준수가 매우 중요"
echo "- 무효 클릭 방지를 위한 사용자 교육 필요"
echo "- 대체 광고 플랫폼도 준비 권장 (네이버 애드포스트 등)"
echo ""
echo "브라우저를 열어서 광고 배치를 확인해보세요!"

if command -v open >/dev/null 2>&1; then
    echo ""
    echo "macOS에서 자동으로 브라우저를 열겠습니다..."
    sleep 2
    open "http://localhost:3000"
fi